import ForestUnimodality.Stage170KernelData.Cell470.Batch000_349
import ForestUnimodality.FiniteKernelGraphBudget

/-! The complete degree domain for one production rectangle, including
every integer shifted index and every real parameter between its endpoints.
The expectation budget and coverage by other rectangles are separate. -/
namespace ForestUnimodality.Stage170KernelData.Cell470

set_option maxRecDepth 100000
set_option maxHeartbeats 0

theorem residual_nonneg_of_degree_le349 (n : ℕ) (hn : n ≤ 349) (j : ℤ)
    {q : ℝ} (hq : q ∈ Set.Icc (interval.lo : ℝ) (interval.hi : ℝ)) :
    0 ≤ row.toReal.residual n j q := by
  interval_cases n
  · exact Kernel000.actual_residual_nonneg j hq
  · exact Kernel001.actual_residual_nonneg j hq
  · exact Kernel002.actual_residual_nonneg j hq
  · exact Kernel003.actual_residual_nonneg j hq
  · exact Kernel004.actual_residual_nonneg j hq
  · exact Kernel005.actual_residual_nonneg j hq
  · exact Kernel006.actual_residual_nonneg j hq
  · exact Kernel007.actual_residual_nonneg j hq
  · exact Kernel008.actual_residual_nonneg j hq
  · exact Kernel009.actual_residual_nonneg j hq
  · exact Kernel010.actual_residual_nonneg j hq
  · exact Kernel011.actual_residual_nonneg j hq
  · exact Kernel012.actual_residual_nonneg j hq
  · exact Kernel013.actual_residual_nonneg j hq
  · exact Kernel014.actual_residual_nonneg j hq
  · exact Kernel015.actual_residual_nonneg j hq
  · exact Kernel016.actual_residual_nonneg j hq
  · exact Kernel017.actual_residual_nonneg j hq
  · exact Kernel018.actual_residual_nonneg j hq
  · exact Kernel019.actual_residual_nonneg j hq
  · exact Kernel020.actual_residual_nonneg j hq
  · exact Kernel021.actual_residual_nonneg j hq
  · exact Kernel022.actual_residual_nonneg j hq
  · exact Kernel023.actual_residual_nonneg j hq
  · exact Kernel024.actual_residual_nonneg j hq
  · exact Kernel025.actual_residual_nonneg j hq
  · exact Kernel026.actual_residual_nonneg j hq
  · exact Kernel027.actual_residual_nonneg j hq
  · exact Kernel028.actual_residual_nonneg j hq
  · exact Kernel029.actual_residual_nonneg j hq
  · exact Kernel030.actual_residual_nonneg j hq
  · exact Kernel031.actual_residual_nonneg j hq
  · exact Kernel032.actual_residual_nonneg j hq
  · exact Kernel033.actual_residual_nonneg j hq
  · exact Kernel034.actual_residual_nonneg j hq
  · exact Kernel035.actual_residual_nonneg j hq
  · exact Kernel036.actual_residual_nonneg j hq
  · exact Kernel037.actual_residual_nonneg j hq
  · exact Kernel038.actual_residual_nonneg j hq
  · exact Kernel039.actual_residual_nonneg j hq
  · exact Kernel040.actual_residual_nonneg j hq
  · exact Kernel041.actual_residual_nonneg j hq
  · exact Kernel042.actual_residual_nonneg j hq
  · exact Kernel043.actual_residual_nonneg j hq
  · exact Kernel044.actual_residual_nonneg j hq
  · exact Kernel045.actual_residual_nonneg j hq
  · exact Kernel046.actual_residual_nonneg j hq
  · exact Kernel047.actual_residual_nonneg j hq
  · exact Kernel048.actual_residual_nonneg j hq
  · exact Kernel049.actual_residual_nonneg j hq
  · exact Kernel050.actual_residual_nonneg j hq
  · exact Kernel051.actual_residual_nonneg j hq
  · exact Kernel052.actual_residual_nonneg j hq
  · exact Kernel053.actual_residual_nonneg j hq
  · exact Kernel054.actual_residual_nonneg j hq
  · exact Kernel055.actual_residual_nonneg j hq
  · exact Kernel056.actual_residual_nonneg j hq
  · exact Kernel057.actual_residual_nonneg j hq
  · exact Kernel058.actual_residual_nonneg j hq
  · exact Kernel059.actual_residual_nonneg j hq
  · exact Kernel060.actual_residual_nonneg j hq
  · exact Kernel061.actual_residual_nonneg j hq
  · exact Kernel062.actual_residual_nonneg j hq
  · exact Kernel063.actual_residual_nonneg j hq
  · exact Kernel064.actual_residual_nonneg j hq
  · exact Kernel065.actual_residual_nonneg j hq
  · exact Kernel066.actual_residual_nonneg j hq
  · exact Kernel067.actual_residual_nonneg j hq
  · exact Kernel068.actual_residual_nonneg j hq
  · exact Kernel069.actual_residual_nonneg j hq
  · exact Kernel070.actual_residual_nonneg j hq
  · exact Kernel071.actual_residual_nonneg j hq
  · exact Kernel072.actual_residual_nonneg j hq
  · exact Kernel073.actual_residual_nonneg j hq
  · exact Kernel074.actual_residual_nonneg j hq
  · exact Kernel075.actual_residual_nonneg j hq
  · exact Kernel076.actual_residual_nonneg j hq
  · exact Kernel077.actual_residual_nonneg j hq
  · exact Kernel078.actual_residual_nonneg j hq
  · exact Kernel079.actual_residual_nonneg j hq
  · exact Kernel080.actual_residual_nonneg j hq
  · exact Kernel081.actual_residual_nonneg j hq
  · exact Kernel082.actual_residual_nonneg j hq
  · exact Kernel083.actual_residual_nonneg j hq
  · exact Kernel084.actual_residual_nonneg j hq
  · exact Kernel085.actual_residual_nonneg j hq
  · exact Kernel086.actual_residual_nonneg j hq
  · exact Kernel087.actual_residual_nonneg j hq
  · exact Kernel088.actual_residual_nonneg j hq
  · exact Kernel089.actual_residual_nonneg j hq
  · exact Kernel090.actual_residual_nonneg j hq
  · exact Kernel091.actual_residual_nonneg j hq
  · exact Kernel092.actual_residual_nonneg j hq
  · exact Kernel093.actual_residual_nonneg j hq
  · exact Kernel094.actual_residual_nonneg j hq
  · exact Kernel095.actual_residual_nonneg j hq
  · exact Kernel096.actual_residual_nonneg j hq
  · exact Kernel097.actual_residual_nonneg j hq
  · exact Kernel098.actual_residual_nonneg j hq
  · exact Kernel099.actual_residual_nonneg j hq
  · exact Kernel100.actual_residual_nonneg j hq
  · exact Kernel101.actual_residual_nonneg j hq
  · exact Kernel102.actual_residual_nonneg j hq
  · exact Kernel103.actual_residual_nonneg j hq
  · exact Kernel104.actual_residual_nonneg j hq
  · exact Kernel105.actual_residual_nonneg j hq
  · exact Kernel106.actual_residual_nonneg j hq
  · exact Kernel107.actual_residual_nonneg j hq
  · exact Kernel108.actual_residual_nonneg j hq
  · exact Kernel109.actual_residual_nonneg j hq
  · exact Kernel110.actual_residual_nonneg j hq
  · exact Kernel111.actual_residual_nonneg j hq
  · exact Kernel112.actual_residual_nonneg j hq
  · exact Kernel113.actual_residual_nonneg j hq
  · exact Kernel114.actual_residual_nonneg j hq
  · exact Kernel115.actual_residual_nonneg j hq
  · exact Kernel116.actual_residual_nonneg j hq
  · exact Kernel117.actual_residual_nonneg j hq
  · exact Kernel118.actual_residual_nonneg j hq
  · exact Kernel119.actual_residual_nonneg j hq
  · exact Kernel120.actual_residual_nonneg j hq
  · exact Kernel121.actual_residual_nonneg j hq
  · exact Kernel122.actual_residual_nonneg j hq
  · exact Kernel123.actual_residual_nonneg j hq
  · exact Kernel124.actual_residual_nonneg j hq
  · exact Kernel125.actual_residual_nonneg j hq
  · exact Kernel126.actual_residual_nonneg j hq
  · exact Kernel127.actual_residual_nonneg j hq
  · exact Kernel128.actual_residual_nonneg j hq
  · exact Kernel129.actual_residual_nonneg j hq
  · exact Kernel130.actual_residual_nonneg j hq
  · exact Kernel131.actual_residual_nonneg j hq
  · exact Kernel132.actual_residual_nonneg j hq
  · exact Kernel133.actual_residual_nonneg j hq
  · exact Kernel134.actual_residual_nonneg j hq
  · exact Kernel135.actual_residual_nonneg j hq
  · exact Kernel136.actual_residual_nonneg j hq
  · exact Kernel137.actual_residual_nonneg j hq
  · exact Kernel138.actual_residual_nonneg j hq
  · exact Kernel139.actual_residual_nonneg j hq
  · exact Kernel140.actual_residual_nonneg j hq
  · exact Kernel141.actual_residual_nonneg j hq
  · exact Kernel142.actual_residual_nonneg j hq
  · exact Kernel143.actual_residual_nonneg j hq
  · exact Kernel144.actual_residual_nonneg j hq
  · exact Kernel145.actual_residual_nonneg j hq
  · exact Kernel146.actual_residual_nonneg j hq
  · exact Kernel147.actual_residual_nonneg j hq
  · exact Kernel148.actual_residual_nonneg j hq
  · exact Kernel149.actual_residual_nonneg j hq
  · exact Kernel150.actual_residual_nonneg j hq
  · exact Kernel151.actual_residual_nonneg j hq
  · exact Kernel152.actual_residual_nonneg j hq
  · exact Kernel153.actual_residual_nonneg j hq
  · exact Kernel154.actual_residual_nonneg j hq
  · exact Kernel155.actual_residual_nonneg j hq
  · exact Kernel156.actual_residual_nonneg j hq
  · exact Kernel157.actual_residual_nonneg j hq
  · exact Kernel158.actual_residual_nonneg j hq
  · exact Kernel159.actual_residual_nonneg j hq
  · exact Kernel160.actual_residual_nonneg j hq
  · exact Kernel161.actual_residual_nonneg j hq
  · exact Kernel162.actual_residual_nonneg j hq
  · exact Kernel163.actual_residual_nonneg j hq
  · exact Kernel164.actual_residual_nonneg j hq
  · exact Kernel165.actual_residual_nonneg j hq
  · exact Kernel166.actual_residual_nonneg j hq
  · exact Kernel167.actual_residual_nonneg j hq
  · exact Kernel168.actual_residual_nonneg j hq
  · exact Kernel169.actual_residual_nonneg j hq
  · exact Kernel170.actual_residual_nonneg j hq
  · exact Kernel171.actual_residual_nonneg j hq
  · exact Kernel172.actual_residual_nonneg j hq
  · exact Kernel173.actual_residual_nonneg j hq
  · exact Kernel174.actual_residual_nonneg j hq
  · exact Kernel175.actual_residual_nonneg j hq
  · exact Kernel176.actual_residual_nonneg j hq
  · exact Kernel177.actual_residual_nonneg j hq
  · exact Kernel178.actual_residual_nonneg j hq
  · exact Kernel179.actual_residual_nonneg j hq
  · exact Kernel180.actual_residual_nonneg j hq
  · exact Kernel181.actual_residual_nonneg j hq
  · exact Kernel182.actual_residual_nonneg j hq
  · exact Kernel183.actual_residual_nonneg j hq
  · exact Kernel184.actual_residual_nonneg j hq
  · exact Kernel185.actual_residual_nonneg j hq
  · exact Kernel186.actual_residual_nonneg j hq
  · exact Kernel187.actual_residual_nonneg j hq
  · exact Kernel188.actual_residual_nonneg j hq
  · exact Kernel189.actual_residual_nonneg j hq
  · exact Kernel190.actual_residual_nonneg j hq
  · exact Kernel191.actual_residual_nonneg j hq
  · exact Kernel192.actual_residual_nonneg j hq
  · exact Kernel193.actual_residual_nonneg j hq
  · exact Kernel194.actual_residual_nonneg j hq
  · exact Kernel195.actual_residual_nonneg j hq
  · exact Kernel196.actual_residual_nonneg j hq
  · exact Kernel197.actual_residual_nonneg j hq
  · exact Kernel198.actual_residual_nonneg j hq
  · exact Kernel199.actual_residual_nonneg j hq
  · exact Kernel200.actual_residual_nonneg j hq
  · exact Kernel201.actual_residual_nonneg j hq
  · exact Kernel202.actual_residual_nonneg j hq
  · exact Kernel203.actual_residual_nonneg j hq
  · exact Kernel204.actual_residual_nonneg j hq
  · exact Kernel205.actual_residual_nonneg j hq
  · exact Kernel206.actual_residual_nonneg j hq
  · exact Kernel207.actual_residual_nonneg j hq
  · exact Kernel208.actual_residual_nonneg j hq
  · exact Kernel209.actual_residual_nonneg j hq
  · exact Kernel210.actual_residual_nonneg j hq
  · exact Kernel211.actual_residual_nonneg j hq
  · exact Kernel212.actual_residual_nonneg j hq
  · exact Kernel213.actual_residual_nonneg j hq
  · exact Kernel214.actual_residual_nonneg j hq
  · exact Kernel215.actual_residual_nonneg j hq
  · exact Kernel216.actual_residual_nonneg j hq
  · exact Kernel217.actual_residual_nonneg j hq
  · exact Kernel218.actual_residual_nonneg j hq
  · exact Kernel219.actual_residual_nonneg j hq
  · exact Kernel220.actual_residual_nonneg j hq
  · exact Kernel221.actual_residual_nonneg j hq
  · exact Kernel222.actual_residual_nonneg j hq
  · exact Kernel223.actual_residual_nonneg j hq
  · exact Kernel224.actual_residual_nonneg j hq
  · exact Kernel225.actual_residual_nonneg j hq
  · exact Kernel226.actual_residual_nonneg j hq
  · exact Kernel227.actual_residual_nonneg j hq
  · exact Kernel228.actual_residual_nonneg j hq
  · exact Kernel229.actual_residual_nonneg j hq
  · exact Kernel230.actual_residual_nonneg j hq
  · exact Kernel231.actual_residual_nonneg j hq
  · exact Kernel232.actual_residual_nonneg j hq
  · exact Kernel233.actual_residual_nonneg j hq
  · exact Kernel234.actual_residual_nonneg j hq
  · exact Kernel235.actual_residual_nonneg j hq
  · exact Kernel236.actual_residual_nonneg j hq
  · exact Kernel237.actual_residual_nonneg j hq
  · exact Kernel238.actual_residual_nonneg j hq
  · exact Kernel239.actual_residual_nonneg j hq
  · exact Kernel240.actual_residual_nonneg j hq
  · exact Kernel241.actual_residual_nonneg j hq
  · exact Kernel242.actual_residual_nonneg j hq
  · exact Kernel243.actual_residual_nonneg j hq
  · exact Kernel244.actual_residual_nonneg j hq
  · exact Kernel245.actual_residual_nonneg j hq
  · exact Kernel246.actual_residual_nonneg j hq
  · exact Kernel247.actual_residual_nonneg j hq
  · exact Kernel248.actual_residual_nonneg j hq
  · exact Kernel249.actual_residual_nonneg j hq
  · exact Kernel250.actual_residual_nonneg j hq
  · exact Kernel251.actual_residual_nonneg j hq
  · exact Kernel252.actual_residual_nonneg j hq
  · exact Kernel253.actual_residual_nonneg j hq
  · exact Kernel254.actual_residual_nonneg j hq
  · exact Kernel255.actual_residual_nonneg j hq
  · exact Kernel256.actual_residual_nonneg j hq
  · exact Kernel257.actual_residual_nonneg j hq
  · exact Kernel258.actual_residual_nonneg j hq
  · exact Kernel259.actual_residual_nonneg j hq
  · exact Kernel260.actual_residual_nonneg j hq
  · exact Kernel261.actual_residual_nonneg j hq
  · exact Kernel262.actual_residual_nonneg j hq
  · exact Kernel263.actual_residual_nonneg j hq
  · exact Kernel264.actual_residual_nonneg j hq
  · exact Kernel265.actual_residual_nonneg j hq
  · exact Kernel266.actual_residual_nonneg j hq
  · exact Kernel267.actual_residual_nonneg j hq
  · exact Kernel268.actual_residual_nonneg j hq
  · exact Kernel269.actual_residual_nonneg j hq
  · exact Kernel270.actual_residual_nonneg j hq
  · exact Kernel271.actual_residual_nonneg j hq
  · exact Kernel272.actual_residual_nonneg j hq
  · exact Kernel273.actual_residual_nonneg j hq
  · exact Kernel274.actual_residual_nonneg j hq
  · exact Kernel275.actual_residual_nonneg j hq
  · exact Kernel276.actual_residual_nonneg j hq
  · exact Kernel277.actual_residual_nonneg j hq
  · exact Kernel278.actual_residual_nonneg j hq
  · exact Kernel279.actual_residual_nonneg j hq
  · exact Kernel280.actual_residual_nonneg j hq
  · exact Kernel281.actual_residual_nonneg j hq
  · exact Kernel282.actual_residual_nonneg j hq
  · exact Kernel283.actual_residual_nonneg j hq
  · exact Kernel284.actual_residual_nonneg j hq
  · exact Kernel285.actual_residual_nonneg j hq
  · exact Kernel286.actual_residual_nonneg j hq
  · exact Kernel287.actual_residual_nonneg j hq
  · exact Kernel288.actual_residual_nonneg j hq
  · exact Kernel289.actual_residual_nonneg j hq
  · exact Kernel290.actual_residual_nonneg j hq
  · exact Kernel291.actual_residual_nonneg j hq
  · exact Kernel292.actual_residual_nonneg j hq
  · exact Kernel293.actual_residual_nonneg j hq
  · exact Kernel294.actual_residual_nonneg j hq
  · exact Kernel295.actual_residual_nonneg j hq
  · exact Kernel296.actual_residual_nonneg j hq
  · exact Kernel297.actual_residual_nonneg j hq
  · exact Kernel298.actual_residual_nonneg j hq
  · exact Kernel299.actual_residual_nonneg j hq
  · exact Kernel300.actual_residual_nonneg j hq
  · exact Kernel301.actual_residual_nonneg j hq
  · exact Kernel302.actual_residual_nonneg j hq
  · exact Kernel303.actual_residual_nonneg j hq
  · exact Kernel304.actual_residual_nonneg j hq
  · exact Kernel305.actual_residual_nonneg j hq
  · exact Kernel306.actual_residual_nonneg j hq
  · exact Kernel307.actual_residual_nonneg j hq
  · exact Kernel308.actual_residual_nonneg j hq
  · exact Kernel309.actual_residual_nonneg j hq
  · exact Kernel310.actual_residual_nonneg j hq
  · exact Kernel311.actual_residual_nonneg j hq
  · exact Kernel312.actual_residual_nonneg j hq
  · exact Kernel313.actual_residual_nonneg j hq
  · exact Kernel314.actual_residual_nonneg j hq
  · exact Kernel315.actual_residual_nonneg j hq
  · exact Kernel316.actual_residual_nonneg j hq
  · exact Kernel317.actual_residual_nonneg j hq
  · exact Kernel318.actual_residual_nonneg j hq
  · exact Kernel319.actual_residual_nonneg j hq
  · exact Kernel320.actual_residual_nonneg j hq
  · exact Kernel321.actual_residual_nonneg j hq
  · exact Kernel322.actual_residual_nonneg j hq
  · exact Kernel323.actual_residual_nonneg j hq
  · exact Kernel324.actual_residual_nonneg j hq
  · exact Kernel325.actual_residual_nonneg j hq
  · exact Kernel326.actual_residual_nonneg j hq
  · exact Kernel327.actual_residual_nonneg j hq
  · exact Kernel328.actual_residual_nonneg j hq
  · exact Kernel329.actual_residual_nonneg j hq
  · exact Kernel330.actual_residual_nonneg j hq
  · exact Kernel331.actual_residual_nonneg j hq
  · exact Kernel332.actual_residual_nonneg j hq
  · exact Kernel333.actual_residual_nonneg j hq
  · exact Kernel334.actual_residual_nonneg j hq
  · exact Kernel335.actual_residual_nonneg j hq
  · exact Kernel336.actual_residual_nonneg j hq
  · exact Kernel337.actual_residual_nonneg j hq
  · exact Kernel338.actual_residual_nonneg j hq
  · exact Kernel339.actual_residual_nonneg j hq
  · exact Kernel340.actual_residual_nonneg j hq
  · exact Kernel341.actual_residual_nonneg j hq
  · exact Kernel342.actual_residual_nonneg j hq
  · exact Kernel343.actual_residual_nonneg j hq
  · exact Kernel344.actual_residual_nonneg j hq
  · exact Kernel345.actual_residual_nonneg j hq
  · exact Kernel346.actual_residual_nonneg j hq
  · exact Kernel347.actual_residual_nonneg j hq
  · exact Kernel348.actual_residual_nonneg j hq
  · exact Kernel349.actual_residual_nonneg j hq

#print axioms residual_nonneg_of_degree_le349
end ForestUnimodality.Stage170KernelData.Cell470

